GenOverlapKey <- function(moltenDischarge,
                          overlapIds=list(),
                          overlapDefinition) {
  #
  # 
  #
  # Args:
  #
  #
  # Returns:
  # 
  
  # get column subset of molten discharge and cast for sum by msdrg
  subset <- moltenDischarge[, c('discharge_id', 'msdrg', 'hosp_id', 'variable', 'value')]
  casted <- dcast(subset, msdrg ~ hosp_id, sum)
  
  
  # flag overlap msdrgs
  overlap <- apply(as.matrix(casted[names(casted) %in% overlapIds]), 1, FUN=overlapDefinition)
  overlapKey <- data.frame(cbind(casted$msdrg, overlap))
  return(overlap)
}

GenPayerKey <- function(moltenDischarge, commercialPayers) {
  #
  # Returns a key of commercial payers, to be used as input for the
  # CastDischarge function
  #
  # Args:
  #   moltenDischarge: the molten discharge data, output of MeltDischarge
  #   commercialPayers: a vector commercial payers, specified by the payer_d
  #     field
  #
  # Returns:
  #   a data frame containing the payer descriptions and a dummy flagging
  #   commercial payers
  
  uniquePayers <- unique(moltenDischarge['payer'])
  commercialDummy <- lapply(uniquePayers, function(x){
                              as.numeric(x %in% commercialPayers)
                            })
  names(commercialDummy) <- c('commercial')
  result <- data.frame(uniquePayers, commercialDummy)
  return(result)
}

GenHospKey <- function() {
  
}

LookupIdByName <- function(hospKey, hospNames) {
  #
  # Returns a vector of ids corresponding to names in hospNames
  #
  # Args:
  #   hospKey: the hospital name/id key generated by GenHospKey
  #   hospNames: a vector of hospital names
  #
  # Returns: 
  #   A vector of hospital ids matching the names in hospNames. Unmatched names
  #   return an Error
  
  subset <- hospKey[hospKey$hosp_name %in% hospNames, ]
  ids <- subset$hosp_id
  if (length(ids) != length(hospNames)) {
    warning("One or more hospital names could not be found in the input key.")
  }
  return(ids)
}

